python -m open_clip_train.main \
    --logs-dir ./logs_debug \
    --name "debug_test0"\
    --save-frequency 1 \
    --accum-freq 24 \
    --log-every-n-steps 1 \
    --save-most-recent \
    --report-to wandb \
    --dataset-type webdataset \
    --train-data="/homes/gws/patxiao/open_clip/mydataset/sample_data/my_sample.tar"  \
    --csv-img-key file \
    --csv-caption-key text \
    --warmup 351 \
    --batch-size=4 \
    --lr=2e-5 \
    --wd=0.1 \
    --epochs=30 \
    --workers=1 \
    --model DINOv2_BiomedBERT \
    --device cuda:3 \
    --train-num-samples 1000 \
    --max_patient_imgs_length 36